### ISSUE TITLE
hedgefetch failed!

### ISSUE THREAD

**Issue by minh-ton** [moosethegoose2213/hedgefetch#1]
`hedgefetch` failed to install successfully therefore it probably needs some `lttstore.com` therapies to not to fail successfully so that some users won't get a fail successfully error while installing `hedgefetch` because of the installation fails successfully ~ 

Nah, just kidding :) great shell script!

**Comment by moosethegoose2213** [comment]
Thank you, I will definitely look into adding more lttstore to the installer for future bug-fixes!
